syntax = "proto3";

package target;

enum ImageType {
  IMAGE_TYPE_UNSPECIFIED = 0;
  IMAGE_TYPE_ORIGINAL = 1;
  IMAGE_TYPE_TRANSFORM = 2;
  IMAGE_TYPE_MARK = 3;
}

message Empty {}

message Position {
  int32 x = 1;
  int32 y = 2;
}

message GetImageRequest { ImageType image_type = 1; }

message GetImageResponse {
  bytes image_data = 1;
  string mime_type = 2;
}

service Target {
  rpc GetPosition(Empty) returns (Position) {}
  rpc SetPosition(Position) returns (Empty) {}
  rpc StreamPosition(Empty) returns (stream Position);
  rpc AdjustImage(Empty) returns (Empty);
  rpc GetImage(GetImageRequest) returns (GetImageResponse);
}